id: I34601142
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:32:26+00:00'
last_modified: '2022-06-07T18:42:17.618010+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24817
  title: བོད་རིག་པའི་གནད་གཞི་ཞིབ་འཇུག་སྦས་དོན་གསལ་བྱེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    74F6:
      image_group_id: I1KG24819
      title: ''
      total_pages: 449
      order: 1
      base_file: 74F6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
