id: P003259
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24817
  title: བོད་རིག་པའི་གནད་གཞི་ཞིབ་འཇུག་སྦས་དོན་གསལ་བྱེད།
  author: ''
  volumes:
    9fcb62852391459793c56e5bb023ed20:
      image_group_id: I1KG24819
      title: ''
      volume_number: 1
      total_pages: 449
      base_file: v001.txt
